version: 0.0
os: linux
files:
  - source: /
    destination: /opt/bitnami/apache/htdocs/cert-master
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install1.sh
      timeout: 300
      runas: root
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
